name: 'Badger'
description: 'Processes gatorgrade achievements and awards badges'
inputs:
  gatorgrade-file:
    description: 'Path to the .gatorgrade file'
    required: true
    default: '.gatorgrade'
outputs:
  badges:
    description: 'Generated badges data'
runs:
  using: 'node16'
  main: 'dist/index.js'